### PR TITLE
Fix messages starting with a prefix being pushed to conversationLog

### PR DESCRIPTION
**Pull request by NanduBit**
It works even with this fault because message starts with ! Doesn't even trigger the message but it will be send to the api request or something like that if it was a previous message. ( I hope if this makes a sense ).

### CODE REVIEW

**Comment by NanduWasTaken** [comment]
I am getting forced!!

**Comment by NanduBit** [comment]
Screenshot_2023-05-14-17-29-07-931

**Review by notunderctrl — APPROVED** [review]

**Comment by NanduBit** [comment]
Why did you change the name it was a good name! 🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by notunderctrl** [comment]
Not very informative 💀

**Pull request merged**
