### PR TITLE
Now bots remembers what it said earlier (improved) 

### PR DESCRIPTION
**Pull request by NanduBit**
I made it so that the bot remembers what it just said earlier before this pull request the bot only knows what the user has said it does not know what it said itself. I saw this problem and thought I could fix this . Then the question arrives why is it use full here is a example of why you would need the bot to remember it's own chats. 
_____________
User: tell me a question.
Bot: what is the colour of the sky.
User: Blue
Bot: I don't understand what did you said? (Lol it only has this much data [ tell me a question and blue ])
______________
Now improved 
_______________
Screenshot_2023-05-04-11-50-47-443

### CODE REVIEW

**Comment by NanduBit** [comment]
Btw love your videos

**Review by notunderctrl — CHANGES_REQUESTED** [review]
Please fix the multiple syntax errors found. Your code editor can help you point these out. Thanks.

**Comment by NanduBit** [comment]
> Please fix the multiple syntax errors found. Your code editor can help you point these out. Thanks.

That was fast yeah I will be doing that right now 😀

**Comment by NanduBit** [comment]
Is it fineeee ?

**Comment by notunderctrl** [comment]
It doesn't seem like the `name` property is supported with `createChatCompletion`. Could you please refer to any documentation/guide you've used for this?

**Review by notunderctrl — APPROVED** [review]
LGTM!

**Pull request merged**
